### ISSUE TITLE
How to generate the fragmentd files?

### ISSUE THREAD

**Issue by shdxiang** [bitmovin/mse-demo#1]
When I use your segments files, it worked.

But if I generate segment files like this:

```
mp4box -dash 4000 -frag 4000 -segment-name segment_ bunny.mp4
```

Chrome will give error:

```
Uncaught (in promise) DOMException: Failed to load because no supported source was found.
```

So could you give me the exact command here, thanks.

**Comment by dweinber** [comment]
You can find details in our blog post: https://bitmovin.com/mp4box-dash-content-generation-x264/
