### ISSUE TITLE
HLS with mse

### ISSUE THREAD

**Issue by XDroiX** [bitmovin/mse-demo#2]
is it possible to do the same with .m3u8 playlist (hls).  fetching segment by segment .ts file?

**Comment by dweinber** [comment]
Theoretically, yes. However, most browsers don't support `.ts` segments directly via the MSE, so you would need to convert the MPEG-2 TS segments to MP4 segments in JavaScript. While this is possible (and the Bitmovin Player supports it), it's definitely out of scope for this demo as it should showcase the basic usage of the MSE.

**Comment by XDroiX** [comment]
ok thank you for your response.
