### ISSUE TITLE
End Duration

### ISSUE THREAD

**Issue by derit** [bitmovin/mse-demo#3]
hello

after i play video, end of video keep waiting stream and play loader

**Comment by dweinber** [comment]
Hi @derit,
This is meant to be a very simple, basic example on how to use the `MediaSource` extension. There are currently no plans to expand it.
However, you might want to look at MediaSource's [endOfStream](https://www.w3.org/TR/media-source/#dom-mediasource-endofstream) function to signal that no more data is expected.
