### ISSUE TITLE
Playing Audio in Video Stream in MSE

### ISSUE THREAD

**Issue by TeamInsideSoftwares** [bitmovin/mse-demo#4]
With this example the video playback works. But how do we add audio to this?.Please share the code.

**Comment by dweinber** [comment]
Please keep in mind that this is and should be an "as simple as possible" example of how to use the `MediaSource` for playback. Therefore, the sample won't be updated to include audio.

Essentially, you would add another `SourceBuffer`, just like it is done for video in https://github.com/bitmovin/mse-demo/blob/d620a9005213837f37474e6e22453db509594e59/index.html#L33
You'll need to change the codec string to match your audio mime type and codec.

The basics of the rest remain the same, you download audio segments in addition and pass it to the `SourceBuffer`. You just need to make sure that you are only adding video segments to the video `SourceBuffer` and audio segments to the audio `SourceBuffer`.
